### ISSUE TITLE
questions about autosync dataset

### ISSUE THREAD

**Issue by ihatedebug** [petuum/autodist#56]
I would like to ask about the dataset that is mentioned in the 'autosync_simulator' branch, 'autodist/simulator/Readme.md'.
In the 'runtimes' folder, 

1. It uses 'run_ncf_single_trial.py' 'run_bert_single_trial.py', ...  and as graph item, 'bert_original_graph_item',...  Could you share these files?
2. Some strategies are named as absolute path ex) 
'--strategy=/home/ubuntu/ncf_dense_pure_random/random_search/0/20200601T080115M902347' while some strategies are ex) '--strategy=PSLoadBalancing_True' or '--strategy=Random16'
What are the difference between  absolute path random search and 'RandomX' ? And What are the difference between the Random{X}s, ex) Random9 and Random16?
3. the length of the list 'runtime' varies. What causes the difference of the length?

Thanks.

**Comment by zhisbug** [comment]
@ihatedebug: the dataset has been re-organized and released. Please check out this [PR#59](https://github.com/petuum/autodist/pull/59) and see whether you have any other problem when playting with the data!
